export const PokeCards = [
  {
    number: "0001",
    name: "Bulbasaur",
    type: ["Grass", "Poison"],
    image: "pending",
    price: 0,
  },
  {
    number: "0002",
    name: "Ivysaur",
    type: ["Grass", "Poison"],
    image: "pending",
    price: 0,
  },
  {
    number: "0003",
    name: "Venusaur",
    type: ["Grass", "Poison"],
    image: "pending",
    price: 0,
  },
  {
    number: "0004",
    name: "Charmander",
    type: ["Fire"],
    image: "pending",
    price: 0,
  },
  {
    number: "0005",
    name: "Charmeleon",
    type: ["Fire"],
    image: "pending",
    price: 0,
  },
  {
    number: "0006",
    name: "Charizard",
    type: ["Fire", "Flying"],
    image: "pending",
    price: 0,
  },
  {
    number: "0007",
    name: "Squirtle",
    type: ["Water"],
    image: "pending",
    price: 0,
  },
  {
    number: "0008",
    name: "Wartortle",
    type: ["Water"],
    image: "pending",
    price: 0,
  },
  {
    number: "0009",
    name: "Blastoise",
    type: ["Water"],
    image: "pending",
    price: 0,
  },
];
